name: Basic Django + React CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Django and dependencies manually
      - name: Install Django Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install django djangorestframework

      # Run Django Tests
      - name: Run Django Tests
        run: |
          source venv/bin/activate
          python manage.py test

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install React dependencies and build frontend
      - name: Build React Frontend
        run: |
          cd frontend
          npm install
          npm run build
